version: 2.1
orbs:
  node: circleci/node@4.2.0
  aws-cli: circleci/aws-cli@2.0.0
  aws-eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  frontend:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: building frontend
          command: yarn frontend:build
      - aws-cli/install
      - run:
          name: deploy frontend
          command: yarn frontend:deploy
  api:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: building api
          command: yarn api:build
      - aws-cli/install
      - aws-eb/setup
      - run:
          name: deploy api
          command: yarn api:deploy

workflows:
  build_and-deploy:
    jobs:
      - frontend:
          filters:
            branches:
              only:
                - main
      - api:
          filters:
            branches:
              only:
                - main
